### ISSUE TITLE
Chat page horizontal scrolling issue

### ISSUE THREAD

**Issue by amative1** [BronyTV/bronytv.net#32]
The "-15" value for the left and right margins of the two info boxes at the bottom causes a horizontal scrollbar to appear and allow for slight horizontal scrolling (with no purpose). Issue occurs on the latest releases of Chrome, Firefox, and Safari (all tested on Mac OS 10.10.5)

**Comment by EndenDragon** [comment]
I fixed it already... but le dusk needs to merge the PR #31

**Comment by omnicons** [comment]
I cannot merge the PR as you've generated conflicts.

I told you I wouldn't merge it. I figured you'd look at it and see why.

**Comment by EndenDragon** [comment]
Welp, ill go redo my localcopy and try another PR. At least tell me why >.< cuz i thought its ok to merge manually.

**Comment by uecasm** [comment]
@omnicons Really bad things happen if commits are on dev but don't get merged to master.  This shouldn't be permitted in the first place.

If you want the option to be able to refuse to merge things, then @EndenDragon has to commit to a PR branch on a local fork, not direct to BTV's dev branch.  (Things have already gone wrong because master has merge commits on it now.  That's not supposed to happen.)

**Comment by EndenDragon** [comment]
#34 Closes this

**Comment by omnicons** [comment]
I wasn't refusing to merge things. I wasn't merging it because it wasn't possible.
